"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useDispatch, useSelector } from "react-redux";
import { setActiveTab } from "../../store/slices/summarySlice";
import {
  HiOutlineDocumentText,
  HiOutlineViewList,
  HiOutlineKey,
  HiOutlineClipboardCopy,
  HiOutlineDownload,
  HiCheck,
  HiOutlineStar,
  HiStar,
} from "react-icons/hi";
import { RiMagicFill } from "react-icons/ri";
import { toggleFavorite } from "../../store/slices/summarySlice";
import toast from "react-hot-toast";

const SENTIMENT_COLORS = {
  positive: "text-jade-400 bg-jade-500/10 border-jade-500/20",
  negative: "text-red-400 bg-red-500/10 border-red-500/20",
  neutral: "text-slate-400 bg-slate-500/10 border-slate-500/20",
  mixed: "text-amber-400 bg-amber-500/10 border-amber-500/20",
};

const TABS = [
  { id: "summary", label: "Summary", icon: HiOutlineDocumentText },
  { id: "bullets", label: "Bullet Points", icon: HiOutlineViewList },
  { id: "keynotes", label: "Key Notes", icon: HiOutlineKey },
];

export default function SummaryOutput({ summary }) {
  const dispatch = useDispatch();
  const { activeTab } = useSelector((s) => s.summary);
  const [copied, setCopied] = useState(false);
  const [isFavorite, setIsFavorite] = useState(summary?.isFavorite || false);

  if (!summary) return null;

  const getActiveContent = () => {
    switch (activeTab) {
      case "summary":
        return summary.summary;
      case "bullets":
        return summary.bulletPoints?.map((b, i) => `${i + 1}. ${b}`).join("\n");
      case "keynotes":
        return summary.keyNotes?.map((k) => `• ${k}`).join("\n");
      default:
        return "";
    }
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(getActiveContent());
      setCopied(true);
      toast.success("Copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Failed to copy");
    }
  };

  const handleDownload = () => {
    const allContent = `# ${summary.title}\n\n## Summary\n${summary.summary}\n\n## Bullet Points\n${summary.bulletPoints?.map((b, i) => `${i + 1}. ${b}`).join("\n")}\n\n## Key Notes\n${summary.keyNotes?.map((k) => `• ${k}`).join("\n")}\n\n---\nGenerated by AI Summarizer | Words: ${summary.wordCount} | Reading time: ${summary.readingTime} min`;
    const blob = new Blob([allContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${summary.title?.replace(/[^a-z0-9]/gi, "-").toLowerCase() || "summary"}.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Downloaded as Markdown");
  };

  const handleToggleFavorite = () => {
    const next = !isFavorite;
    setIsFavorite(next);
    dispatch(toggleFavorite({ id: summary._id, isFavorite: next }));
    toast.success(next ? "Added to favorites" : "Removed from favorites");
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="border border-ink-700 rounded-2xl overflow-hidden"
    >
      {/* Header */}
      <div className="px-5 py-4 border-b border-ink-700 bg-ink-800/40">
        <div className="flex items-start justify-between gap-3">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <RiMagicFill className="text-jade-400 text-sm flex-shrink-0" />
              <span className="text-xs font-mono text-jade-400 uppercase tracking-widest">
                AI Summary
              </span>
            </div>
            <h3 className="text-white font-medium text-sm leading-snug truncate">
              {summary.title}
            </h3>
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            {/* Meta badges */}
            <div className="hidden sm:flex items-center gap-1.5">
              <span className="text-xs text-slate-600 font-mono">
                {summary.wordCount}w
              </span>
              <span className="text-slate-700">·</span>
              <span className="text-xs text-slate-600 font-mono">
                {summary.readingTime}m read
              </span>
              {summary.sentiment && (
                <>
                  <span className="text-slate-700">·</span>
                  <span
                    className={`text-xs px-2 py-0.5 rounded-full border capitalize ${SENTIMENT_COLORS[summary.sentiment] || SENTIMENT_COLORS.neutral}`}
                  >
                    {summary.sentiment}
                  </span>
                </>
              )}
            </div>
            {/* Actions */}
            <button
              onClick={handleToggleFavorite}
              className="p-1.5 rounded-lg text-slate-500 hover:text-amber-400 hover:bg-amber-500/5 transition-colors"
            >
              {isFavorite ? (
                <HiStar className="text-amber-400" />
              ) : (
                <HiOutlineStar />
              )}
            </button>
            <button
              onClick={handleCopy}
              className="p-1.5 rounded-lg text-slate-500 hover:text-jade-400 hover:bg-jade-500/5 transition-colors"
            >
              {copied ? (
                <HiCheck className="text-jade-400" />
              ) : (
                <HiOutlineClipboardCopy />
              )}
            </button>
            <button
              onClick={handleDownload}
              className="p-1.5 rounded-lg text-slate-500 hover:text-jade-400 hover:bg-jade-500/5 transition-colors"
            >
              <HiOutlineDownload />
            </button>
          </div>
        </div>

        {/* Tags */}
        {summary.tags?.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mt-3">
            {summary.tags.map((tag) => (
              <span
                key={tag}
                className="text-xs px-2 py-0.5 bg-ink-700 text-slate-500 rounded-full"
              >
                #{tag}
              </span>
            ))}
          </div>
        )}
      </div>

      {/* Tabs */}
      <div className="flex border-b border-ink-700">
        {TABS.map((tab) => {
          const Icon = tab.icon;
          return (
            <button
              key={tab.id}
              onClick={() => dispatch(setActiveTab(tab.id))}
              className={`flex-1 flex items-center justify-center gap-1.5 px-3 py-3 text-xs font-medium transition-colors relative ${
                activeTab === tab.id
                  ? "text-jade-400"
                  : "text-slate-500 hover:text-slate-300"
              }`}
            >
              <Icon className="text-sm" />
              {tab.label}
              {activeTab === tab.id && (
                <motion.div
                  layoutId="tab-indicator"
                  className="absolute bottom-0 left-0 right-0 h-0.5 bg-jade-500"
                />
              )}
            </button>
          );
        })}
      </div>

      {/* Content */}
      <AnimatePresence mode="wait">
        <motion.div
          key={activeTab}
          initial={{ opacity: 0, y: 6 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -6 }}
          transition={{ duration: 0.2 }}
          className="p-5"
        >
          {activeTab === "summary" && (
            <p className="text-slate-300 text-sm leading-relaxed">
              {summary.summary}
            </p>
          )}

          {activeTab === "bullets" && (
            <ul className="space-y-3">
              {summary.bulletPoints?.map((point, i) => (
                <motion.li
                  key={i}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.06 }}
                  className="flex items-start gap-3"
                >
                  <span className="flex-shrink-0 w-5 h-5 rounded-full bg-jade-500/10 border border-jade-500/30 flex items-center justify-center text-jade-400 text-xs font-mono mt-0.5">
                    {i + 1}
                  </span>
                  <span className="text-slate-300 text-sm leading-relaxed">
                    {point}
                  </span>
                </motion.li>
              ))}
            </ul>
          )}

          {activeTab === "keynotes" && (
            <ul className="space-y-3">
              {summary.keyNotes?.map((note, i) => (
                <motion.li
                  key={i}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.08 }}
                  className="flex items-start gap-3 p-3 bg-ink-800/60 rounded-xl border border-ink-700"
                >
                  <HiOutlineKey className="text-amber-400 text-sm flex-shrink-0 mt-0.5" />
                  <span className="text-slate-300 text-sm leading-relaxed">
                    {note}
                  </span>
                </motion.li>
              ))}
            </ul>
          )}
        </motion.div>
      </AnimatePresence>

      {/* Transcription (if audio) */}
      {summary.transcribedText && (
        <details className="border-t border-ink-700 group">
          <summary className="px-5 py-3 text-xs text-slate-500 cursor-pointer hover:text-slate-400 transition-colors select-none flex items-center gap-1.5">
            <span className="group-open:rotate-90 transition-transform inline-block">
              ▶
            </span>
            View transcription
          </summary>
          <div className="px-5 pb-4">
            <p className="text-xs text-slate-500 leading-relaxed font-mono bg-ink-800 rounded-lg p-3 border border-ink-700">
              {summary.transcribedText}
            </p>
          </div>
        </details>
      )}
    </motion.div>
  );
}
